<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="saurav_041" failures="4" tests="16" name="com.zerobank.runners.TestNGRunner" time="220.051" errors="0" timestamp="2025-03-22T17:02:40 IST" skipped="0">
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="17.780"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="16.697"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="16.459">
    <failure message="Error message is not displayed expected [Insufficient Balance.] but found [You successfully submitted your transaction.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message is not displayed expected [Insufficient Balance.] but found [You successfully submitted your transaction.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.zerobank.steps.FundTransferStepDefinition.error_should_be_displayed(FundTransferStepDefinition.java:127)
at ✽.Error "Insufficient Balance." should be displayed(file:///C:/Users/saura/OneDrive/Desktop/Wipro_Testing_Training/Project_Workspace/ZeroBank_Capstone_Project/src/test/resources/features/03_FundTransfer.feature:22)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="14.223"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="13.850">
    <failure message="Error message is not displayed expected [Amount field cannot be empty.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message is not displayed expected [Amount field cannot be empty.] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.zerobank.steps.PayBillsStepDefinition.user_can_see_the_error(PayBillsStepDefinition.java:65)
at ✽.User can see the error "Amount field cannot be empty."(file:///C:/Users/saura/OneDrive/Desktop/Wipro_Testing_Training/Project_Workspace/ZeroBank_Capstone_Project/src/test/resources/features/04_PayBills.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="17.362">
    <failure message="Error message is not displayed expected [All fields are required.] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message is not displayed expected [All fields are required.] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.zerobank.steps.AddPayeeStepDefinition.user_can_see_the_error_meesage(AddPayeeStepDefinition.java:63)
at ✽.User can see the error meesage "All fields are required."(file:///C:/Users/saura/OneDrive/Desktop/Wipro_Testing_Training/Project_Workspace/ZeroBank_Capstone_Project/src/test/resources/features/05_AddPayee.feature:22)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="6.200"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="13.095"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="13.527"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="11.703"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="18.470"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="12.725"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="6.685"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="13.131"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="14.663"/>
  <testcase classname="com.zerobank.runners.TestNGRunner" name="runScenario" time="13.481">
    <failure message="Error message is not displayed expected [Invalid Amount.] but found [You successfully submitted your transaction.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error message is not displayed expected [Invalid Amount.] but found [You successfully submitted your transaction.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at com.zerobank.steps.FundTransferStepDefinition.error_should_be_displayed(FundTransferStepDefinition.java:127)
at ✽.Error "Invalid Amount." should be displayed(file:///C:/Users/saura/OneDrive/Desktop/Wipro_Testing_Training/Project_Workspace/ZeroBank_Capstone_Project/src/test/resources/features/03_FundTransfer.feature:33)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.zerobank.runners.TestNGRunner -->
